name: xeditor
description: "Editor de texto personal"

publish_to: 'none' # Prevent accidental publishing to pub.dev
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Paquetes adicionales para funcionalidades del editor de texto
  file_picker: ^8.1.3            # Para abrir y guardar archivos
  flutter_colorpicker: ^1.1.0     # Selector de color para personalizar el text
  flutter_quill: ^10.8.5
  flutter_quill_extensions: ^10.8.5
  font_awesome_flutter: ^10.7.0
  path_provider: ^2.1.5
  docx_template: ^0.4.0
  pdfx: ^2.8.0
  syncfusion_flutter_pdf: ^27.1.57
  syncfusion_flutter_pdfviewer: ^27.1.57
  xml: ^6.1.0
  pdfrx: ^1.0.84
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Agregar fuentes personalizadas (si tienes archivos de fuentes en assets/fonts/)
  fonts:
    - family: MrsSaintDelafield-Regular
      fonts:
        - asset: assets/fonts/Mrs_Saint_Delafield/MrsSaintDelafield-Regular.ttf
    - family: NothingYouCouldDo-Regular
      fonts:
        - asset: assets/fonts/Nothing_You_Could_Do/NothingYouCouldDo-Regular.ttf
    - family: Parisienne-Regular
      fonts:
        - asset: assets/fonts/Parisienne/Parisienne-Regular.ttf

  # Sección de assets si necesitas agregar imágenes o archivos de otros recursos
  assets:
    - assets/fonts/
  